In [2]:
import pandas as pd

In [6]:
ruta_corpus = "../../data/processed/corpus_date_formatted.xlsx"

corpus_completo = pd.read_excel(ruta_corpus, engine="openpyxl")

corpus_completo.head()

,Diario,Autor,Fecha,Título,Texto,Vínculo,ID
0,El Espectador,Gonzalo Hernández,2018-01-01,Fajardo: para nada tibio,"La Coalición Colombia –Partido Alianza Verde, ...",https://web.archive.org/web/20180102104221/htt...,1
1,El Espectador,Eduardo Barajas Sandoval,2018-01-01,Macedonia de Norte,Las interpretaciones de la historia sirven com...,https://web.archive.org/web/20180102104221/htt...,2
2,El Espectador,Daniel Emilio Rojas Castro,2018-01-01,El nacionalismo según Vargas Llosa,La semana pasada Mario Vargas Llosa publicó un...,https://web.archive.org/web/20180102104221/htt...,3
3,El Espectador,Reinaldo Spitaletta,2018-01-01,"Tiempo sagrado, tiempo profano","Pudiera decirse, sin ser una verdad absoluta, ...",https://web.archive.org/web/20180102104221/htt...,4
4,El Espectador,Aura Lucía Mera,2018-01-01,La rebelión de los bueyes,Lo mejor del encierro de Las Ventas fueron los...,https://web.archive.org/web/20180102104221/htt...,5

In [8]:
ruta_id_doc_admin = "../../data/auxiliar/id_doc_admin.txt"

with open(ruta_id_doc_admin, "r", encoding="utf-8") as f:
    id_doc_admin = [line.strip() for line in f if line.strip()]

id_doc_admin[:20]

['id_doc',
 '8392',
 '13580',
 '4241',
 '3625',
 '288',
 '5077',
 '12629',
 '11301',
 '9456',
 '7180',
 '5767',
 '6863',
 '1302',
 '4017',
 '952',
 '4027',
 '5930',
 '11211',
 '6417']

In [9]:
id_doc_admin = id_doc_admin[1:]
id_doc_admin_int = [int(x) for x in id_doc_admin]

corpus_filtrado = corpus_completo[corpus_completo["ID"].isin(id_doc_admin_int)].copy()
corpus_filtrado.head()

,Diario,Autor,Fecha,Título,Texto,Vínculo,ID
9,El Espectador,Luis I. Sandoval M.,2018-01-01,"Clara, Humberto, Gustavo: la esperanza","Apreciada candidata Clara López, apreciados ca...",https://web.archive.org/web/20180102104221/htt...,10
10,El Espectador,Pascual Gaviria,2018-01-02,Elecciones típicas,El método es sencillo. Primero tensar un poco ...,https://web.archive.org/web/20180103111621/htt...,11
14,El Espectador,Marcos Peckel,2018-01-02,Autócratas,El paisaje político en los cinco continentes s...,https://web.archive.org/web/20180103111621/htt...,15
26,El Espectador,Vivian Newman,2018-01-05,Deliberación en la división,¿Qué hace que miembros de sociedades divididas...,https://web.archive.org/web/20180105115107/htt...,27
30,El Espectador,Carolina Botero Cabrera,2018-01-05,Retos en la ciberpolítica de 2018 (II),2018 será un año muy movido en ciberpolítica. ...,https://web.archive.org/web/20180105115107/htt...,31

In [10]:
ruta_salida = "../../data/columnas_admin_ciencia.xlsx"
corpus_filtrado.to_excel(ruta_salida, index=False, engine="openpyxl")